sudo: false
language: cpp
git:
  submodules: false

matrix:
  allow_failures:
    - env: _CXX=clang++-3.8 _CC=clang-3.8 COMPILER_NAME=clang-3.8
  include:
    - env: _CXX=g++-5 _CC=gcc-5 COMPILER_NAME=gcc
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
    - env: _CXX=clang++-3.7 _CC=clang-3.7 COMPILER_NAME=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
          sources: *sources
    - env: _CXX=clang++-3.8 _CC=clang-3.8 COMPILER_NAME=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

install:
  - export CXX="$_CXX" CC="$_CC"

before_script:
  - make clean
  - make git

script:
  - make all
  - make test

before_deploy:
  - make pack-release

deploy:
  provider: releases
  api_key:
    secure: bPtQT10pEJamkOKrVJ3Y0aAxKX27UeYAmJo+mdyH2qBcwhOKoE6r/To+kvRFAq25Df7tVa7MDEMLv7eXjb2ouVhP9R3YbZ+opbEKd+zQ5CI+RidktpkZpwaOvMJuSDsbd6sABfv1Jlg3WuDVipzS47HGZDfo8PaQYWYRLvqRULpePFjmYhGsma29p8sw1ewmbp2qA+QsU6mQi3KhJci2lwFVrLiG9GEhSGOTyQ3yjBlYBCdtv0rLlHjjcgwwxlD9i6HjEbW6LAK+IiZHGP5AHUHfbumSEFsBJkdMqY/5HkxnM+sm09Kop4VDlVUEvUkW7GAbuCWXIhn5Rq1VWxupVBxrTzLJRqnbf/zV2CFqa0EifPC2H/c2D2ueeWbrKsg/B6KaOJRKHFCdqhtzq2QFxtXdWKbhvx+hAmdJKyIOmW5G5VfVJo1/sdKa78EfHhRKCWGKJ6ZpC7Hq+GlhKv4KPkQzwrHTvbeyfxjGPqF8mqYlhoEt3Mhxbn4pgagHM945eK7fOYPbDXaz9Z/vAOfLBy1mJYOok27noa3EU63VWjDue4hK/1Vf/fzOBsntSahBKDRN9GIfmysZsxYP2FEMTeqgkE57CrnYuTHjhcRe7kEdBvogzbdaPxOwiFry3mjuYTya65+G+YnkthC6G+EXO5SdNkN/qFYSefF7MLdK0qw=
  file: release_$COMPILER_NAME.tar.bz2
  on:
    tags: true
    repo: nabijaczleweli/libYAML-wrapper
