sudo: false
language: cpp

git:
  submodules: false

compiler:
  - gcc
  - clang

env:
  - TEST_COVERAGE=true
  - TEST_COVERAGE=false

matrix:
  exclude:
    - compiler: clang
      env: TEST_COVERAGE=true

install:
  - if [ "$TEST_COVERAGE" ]; then pip install --user `whoami` cpp-coveralls; fi
  - export COMPILER_NAME=$CC
  - if [ "$CXX" = "g++" ]; then export CXX=g++-5 CC=gcc-5; fi
  - if [ "$CXX" = "clang++" ]; then export CXX=clang++-3.7 CC=clang-3.7; fi

before_deploy:
  - make pack-release

deploy:
  provider: releases
  api_key:
    secure: bPtQT10pEJamkOKrVJ3Y0aAxKX27UeYAmJo+mdyH2qBcwhOKoE6r/To+kvRFAq25Df7tVa7MDEMLv7eXjb2ouVhP9R3YbZ+opbEKd+zQ5CI+RidktpkZpwaOvMJuSDsbd6sABfv1Jlg3WuDVipzS47HGZDfo8PaQYWYRLvqRULpePFjmYhGsma29p8sw1ewmbp2qA+QsU6mQi3KhJci2lwFVrLiG9GEhSGOTyQ3yjBlYBCdtv0rLlHjjcgwwxlD9i6HjEbW6LAK+IiZHGP5AHUHfbumSEFsBJkdMqY/5HkxnM+sm09Kop4VDlVUEvUkW7GAbuCWXIhn5Rq1VWxupVBxrTzLJRqnbf/zV2CFqa0EifPC2H/c2D2ueeWbrKsg/B6KaOJRKHFCdqhtzq2QFxtXdWKbhvx+hAmdJKyIOmW5G5VfVJo1/sdKa78EfHhRKCWGKJ6ZpC7Hq+GlhKv4KPkQzwrHTvbeyfxjGPqF8mqYlhoEt3Mhxbn4pgagHM945eK7fOYPbDXaz9Z/vAOfLBy1mJYOok27noa3EU63VWjDue4hK/1Vf/fzOBsntSahBKDRN9GIfmysZsxYP2FEMTeqgkE57CrnYuTHjhcRe7kEdBvogzbdaPxOwiFry3mjuYTya65+G+YnkthC6G+EXO5SdNkN/qFYSefF7MLdK0qw=
  file: release_$COMPILER_NAME.tar.bz2
  on:
    tags: true
    repo: nabijaczleweli/libYAML-wrapper

before_script:
  - make clean
  - make git

script:
  - make all
  - make test

after_success:
  - if [ "$TEST_COVERAGE" ]; then coveralls --root src --build-root out --exclude bandit --exclude libyaml --exclude test --gcov-options '\-lp'; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-5
      - g++-5
      - clang-3.7
